services:
  spark-master:
    image: docker.io/apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ..:/workspace
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master

  spark-worker-1:
    image: docker.io/apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ..:/workspace
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077

  spark-worker-2:
    image: docker.io/apache/spark:4.0.1-scala2.13-java17-python3-r-ubuntu
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ..:/workspace
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
